### ISSUE TITLE
errno 107

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/fs2-io_uring#33]
```
[info] ==> X fs2.io.uring.net.TcpSocketSuite.readN yields chunks of the requested size 0.01s java.io.IOException: 107
```

**Comment by LeeTibbert** [comment]
You have probably figured it out already. For posterity, errno 107 is, I believe, "Socket not connected".  

I'll look a the test when I can to see what timing glitch may exist.  Does it happen regularly or intermittently?

**Comment by armanbilge** [comment]
> You have probably figured it out already.

Heh, I have not. Thanks for taking a look!

> Does it happen regularly or intermittently?

It happens regularly in CI, but not always. I have never seen it locally.

https://github.com/armanbilge/fs2-io_uring/actions/runs/3543014683/jobs/6094704269

**Comment by LeeTibbert** [comment]
Thank you for the URL capturing the malefactor in the act:  test("readN yields chunks of the requested size").
The traceback helps focus my debugging. 

I've forked & cloned the repository and am on the ramp-up to learn some FS2.

**Comment by LeeTibbert** [comment]
I am working my way through tracing and learning fs2-io as I go. 

I have a hunch that there are two levels and both are worth fixing.
That is, the intermittent ENOTCONN is telling us something.
I need to learn _a_lot_ more in order to be able to convert my
hunch to evidence.

>  client.concurrently(junkServer)

IIUC,  this line starts the client and the client & junkServer run at the "same" logical
time. Has the junkServer been previously started?  I think not.  

The server needs to come up and stabilize, at least until it gets into 
accept() (a bit of a fib, there is a window between mid-listen() and mid-accept()
which the RFCs describe.)

This reminds me of an issue in epollcat that Arman & I worked on.

I need to rat around and find the server initialization code where it calls C
(and what .evalTaps it does) and the client connect() code, how the sqe's (?)
are set up and submitted.

In the past few days I have corrected a problem in SN with `poll()` and the
way it was ~~dropping~~ handling connection refusal so my mind is
predisposed that way.

A good problem to chew on.

**Comment by armanbilge** [comment]
> Has the junkServer been previously started? I think not.

The server is started here, as part of the `setup`:
https://github.com/armanbilge/fs2-io_uring/blob/15f672763ed3b2279cdadadb045c6eb64a5b7a8a/uring/src/test/scala/fs2/io/uring/net/TcpSocketSuite.scala#L102-L105

https://github.com/armanbilge/fs2-io_uring/blob/15f672763ed3b2279cdadadb045c6eb64a5b7a8a/uring/src/test/scala/fs2/io/uring/net/TcpSocketSuite.scala#L56-L60

The `serverResource` method first binds and then listens before returning the address.
https://github.com/armanbilge/fs2-io_uring/blob/15f672763ed3b2279cdadadb045c6eb64a5b7a8a/uring/src/main/scala/fs2/io/uring/net/UringSocketGroup.scala#L88

**Comment by armanbilge** [comment]
More stack trace:
```
java.io.IOException: 107
[error]     at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
[error]     at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
[error]     at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
[error]     at java.lang.StackTrace$.currentStackTrace(Unknown Source)
[error]     at java.lang.Throwable.fillInStackTrace(Unknown Source)
[error]     at fs2.io.uring.IOExceptionHelper$.apply(Unknown Source)
[error]     at fs2.io.uring.Uring$$anon$1.$anonfun$apply$9(Unknown Source)
[error]     at fs2.io.uring.Uring$$anon$1$$Lambda$5.apply(Unknown Source)
[error]     at cats.ApplicativeError.$anonfun$raiseWhen$1(Unknown Source)
[error]     at cats.ApplicativeError$$Lambda$1.apply(Unknown Source)
[error]     at cats.Applicative.whenA(Unknown Source)
[error]     at void @ fs2.io.uring.net.UringSocketGroup.closeSocket(Unknown Source)
[error]     at delay @ fs2.io.uring.Uring$$anon$1.$anonfun$apply$2(Unknown Source)
[error]     at flatMap @ fs2.io.uring.Uring$$anon$1.$anonfun$apply$2(Unknown Source)
[error]     at flatTap @ fs2.io.uring.Uring$$anon$1.$anonfun$apply$2(Unknown Source)
[error]     at uncancelable @ fs2.io.uring.Uring$$anon$1.$anonfun$apply$1(Unknown Source)
[error]     at cont @ fs2.io.uring.Uring.exec(Unknown Source)
[error]     at void @ fs2.io.uring.net.UringSocketGroup.closeSocket(Unknown Source)
[error]     at uncancelable @ fs2.Compiler$Target.uncancelable(Unknown Source)
[error]     at flatMap @ fs2.Compiler$Target.flatMap(Unknown Source)
[error]     at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Unknown Source)
[error]     at modify @ fs2.internal.Scope.close(Unknown Source)
[error]     at flatMap @ fs2.Compiler$Target.flatMap(Unknown Source)
[error]     at flatMap @ fs2.Compiler$Target.flatMap(Unknown Source)
[error]     at flatMap @ fs2.Compiler$Target.flatMap(Unknown Source)
[error]     at flatMap @ fs2.Compiler$Target.flatMap(Unknown Source)
```

It seems that a socket raising `ENOTCONN` on `close()` is quite unusual 🤔

**Comment by antoniojimeneznieto** [comment]
Hello! :)

I've come across the identical -107 (ENOTCONN) issue within the JVM's Netty io_uring. This error appears tied to operation 34, which involves socket shutdown. Through repeated tests and some debugging, I think I could have found the root of the problem: we're attempting to shut down a socket that's already closed, hence triggering the -107 error. 

Here's an example:
```
...
[HANDLE CQCB 34]: fd: 68, res: 0, flags: 0, op: 19, data: 10 // op 19 == CLOSE and the fd is 68 which is the fd that we try to shutdown later.

// More operations

[HANDLE CQCB 38]: fd: 66, res: 68, flags: 0, op: 13, data: 11
[SQ 50] Enqueuing a new Sqe with: OP: 26, flags: 0, rwFlags: 0, fd: 68, bufferAddress: 140060896962224, length: 30, offset: 0, extraData: 10
[HANDLE CQCB 50]: fd: 68, res: 30, flags: 0, op: 26, data: 10
[SQ 50] Enqueuing a new Sqe with: OP: 34, flags: 0, rwFlags: 0, fd: 68, bufferAddress: 0, length: 1, offset: 0, extraData: 10
[HANDLE CQCB 50]: fd: 68, res: -107, flags: 0, op: 34, data: 10 // We tried to shutdown a closed socket.
...
```

Here it is the stack trace of this case:

```
X fs2.io.uring.net.TcpSocketSuit.readN yields chunks of the requested size  0.725s java.io.IOException: Error in completion queue entry of the ring with fd: 42 with fd: 68 op: 34 res: -107 and data: 10
    at fs2.io.uring.unsafe.UringSystem$Poller$$anon$2.handleCallback$1(UringSystem.scala:378)
    at fs2.io.uring.unsafe.UringSystem$Poller$$anon$2.$anonfun$handle$1(UringSystem.scala:400)
    at fs2.io.uring.unsafe.UringSystem$Poller$$anon$2.$anonfun$handle$1$adapted(UringSystem.scala:399)
    at scala.Option.foreach(Option.scala:437)
    at fs2.io.uring.unsafe.UringSystem$Poller$$anon$2.handle(UringSystem.scala:399)
    at io.netty.incubator.channel.uring.UserData.decode(UserData.java:30)
    at io.netty.incubator.channel.uring.IOUringCompletionQueue.process(IOUringCompletionQueue.java:90)
    at io.netty.incubator.channel.uring.UringCompletionQueue.process(UringRing.scala:370)
    at fs2.io.uring.unsafe.UringSystem$Poller.process(UringSystem.scala:368)
    at fs2.io.uring.unsafe.UringSystem$Poller.poll(UringSystem.scala:358)
    at fs2.io.uring.unsafe.UringSystem$.poll(UringSystem.scala:74)
    at fs2.io.uring.unsafe.UringSystem$.poll(UringSystem.scala:50)
    at async_ @ fs2.io.uring.unsafe.UringSystem$ApiImpl$$anon$1.$anonfun$apply$2(UringSystem.scala:166)
    at flatMap @ fs2.io.uring.unsafe.UringSystem$ApiImpl$$anon$1.$anonfun$apply$2(UringSystem.scala:175)
    at flatTap @ fs2.io.uring.unsafe.UringSystem$ApiImpl$$anon$1.$anonfun$apply$2(UringSystem.scala:188)
    at uncancelable @ fs2.io.uring.unsafe.UringSystem$ApiImpl$$anon$1.$anonfun$apply$1(UringSystem.scala:165)
    at cont @ fs2.io.uring.unsafe.UringSystem$ApiImpl.exec(UringSystem.scala:161)
    at void @ fs2.io.uring.net.TcpSocketSuit.$anonfun$new$59(TcpSocketSuite.scala:310)
    at uncancelable @ fs2.Compiler$Target.uncancelable(Compiler.scala:165)
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
    at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:161)
    at modify @ fs2.internal.Scope.close(Scope.scala:262)
3
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
```

**Comment by armanbilge** [comment]
> This error appears tied to operation 34, which involves socket shutdown.

Ahhhh 🤦that makes a lot more sense. 107 is a possible error for [`shutdown`](https://man7.org/linux/man-pages/man2/shutdown.2.html). For some reason I thought it was an error on `close` which wasn't making sense ... 😅

Thanks, this is very helpful 🙏I will take another look now that I properly understand the problem 😂

**Comment by armanbilge** [comment]
After going crazy for a couple days Antonio and I finally tracked this down. It looks like `ENOTCONN` is a typical result when using `shutdown` and other runtimes such as the JVM and Node.js are just ignoring it. So we can do the same.

https://github.com/openjdk/jdk/blob/dcd6e756718b656d43f4575558f41ce0c28d0eca/src/java.base/unix/native/libnio/ch/Net.c#L844-L851

**Comment by armanbilge** [comment]
See also: https://bugs.openjdk.org/browse/JDK-4516760
