### ISSUE TITLE
Replace `Semaphore(1)` with `Mutex`

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/fs2-io_uring#60]
After we update to Cats Effect 3.5.x.

**Comment by antoniojimeneznieto** [comment]
I am going to take care of this :)

**Comment by armanbilge** [comment]
@antoniojimeneznieto thanks! I just merged https://github.com/armanbilge/fs2-io_uring/pull/63 which includes the CE 3.5 upgrade.
