### ISSUE TITLE
Switch ARM CI to Cirrus

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/fs2-io_uring#64]
We've been using it in Cats Effect happily :)

**Comment by antoniojimeneznieto** [comment]
Interesting, I'm going to learn more about Cirrus and how it is used in Cats Effect

**Comment by armanbilge** [comment]
Config is here: https://github.com/typelevel/cats-effect/blob/ab5d56c6a6cb2ef7484e5ecb881ecf6b85ff61dc/.cirrus.yml

**Comment by armanbilge** [comment]
I looked at this a bit, unfortunately I don't think we are going to able to use Cirrus for testing fs2-io_uring on ARM at the moment.

The problem is it seems to be using a pretty old Linux kernel version.

```
uname -a
Linux cirrus-ci-task-5597057642135552 5.4.209-116.367.amzn2.aarch64 #1 SMP Wed Aug 31 00:10:02 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

For comparison, this is what we have on Circle CI currently.

```
Linux ip-10-0-24-4 5.15.0-1033-aws #37~20.04.1-Ubuntu SMP Fri Mar 17 11:39:18 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
